algoritmo "semnome"
// Função :
// Autor :
// Data : 23/03/2022
// Seção de Declarações
var
   n : inteiro
Procedimento Parouimpar (v: inteiro)
inicio

      Se (v %2 = 0) entao
         Escreval ("O numero", v, " é par")
      senao
           Escreval ("O número", v, " é ímpar")
      fimse
Fimprocedimento
inicio
// Seção de Comandos
Escreva ("Digite um numero: ")
Leia (n)
Parouimpar (n)
fimalgoritmo
