algoritmo "Somaparametrosreferencia"
// Função :
// Autor :
// Data : 23/03/2022
// Seção de Declarações 
var
   x, y: inteiro
Procedimento Soma(var a, b: inteiro)
Inicio
a <- a + 1
b <- b + 2
Escreval ("Valor de A = ", a)
Escreval ("Valor de B = ", b)
Escreval ("Soma A + B = ", a+b)
FimProcedimento
inicio
// Seção de Comandos 
x <- 4
y <- 8
Soma (x, y)
Escreval ("Valor de X = ", x)
Escreval ("Valor de y = ", y)
fimalgoritmo
